name: Flutter CI

on:
  push:
    branches: [ "main" ]


  pull_request:
    branches: [ "main" ]

jobs:
    flutter_jobs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          
        
    
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
    
        - name: Install dependencies
          run: flutter pub get
          working-directory: mobile/ecommerce-tdd/ecommerce_a2sv
    
        - name : Run tests
          run: flutter test
          working-directory: mobile/ecommerce-tdd/ecommerce_a2sv
